import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts', 'tests/**/*.test.ts'],
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      // Only the pure modules under test are measured; pulling untested UI
      // into the denominator would make the number meaningless.
      include: [
        'src/lib/shared/collections/move-item.ts',
        'src/components/media/media-page/media-page-format.tsx',
        'src/components/media/media-page/proposal-session-merge.ts',
        'src/components/media/media-editor/media-editor-helpers.ts',
        'src/components/media/media-editor/media-editor-derived.ts',
        'src/components/media/pr-editor/pr-editor-change-summary.ts',
        'src/lib/github/proposal-diff.ts',
        'src/lib/media/saga/saga-grouping.ts',
        'src/lib/local/folder-match.ts',
        'src/lib/local/season-resolve.ts',
        'src/lib/local/catalog-game-linking.ts',
        'src/lib/local/rom-name-parser.ts',
        'src/lib/local/rom-rename-plan.ts',
        'src/lib/local/formatters.ts',
        'src/lib/local/status-badge.ts',
        'src/lib/player/queue.ts',
        'src/lib/player/progress-rules.ts',
        'src/lib/player/keymap.ts',
        'src/lib/player/format-time.ts',
        'src/lib/ui-themes/variables-block.ts',
        'src/lib/ui-themes/ui-theme-loader.ts',
        'src/lib/welcome/onboarding-steps.ts',
        'src/lib/welcome/guide-content.ts',
        'src/lib/welcome/guide-search.ts',
        'src/lib/welcome/settings-tabs.ts',
        'src/lib/media/creator-completion.ts',
        'src/lib/company/company-works.ts',
        'src/lib/company/company-page-id.ts',
        'src/lib/big-picture/focus-grid.ts',
        'src/lib/big-picture/gamepad.ts',
        'src/lib/big-picture/glyphs.ts',
        'src/lib/big-picture/categories.ts',
        'src/lib/big-picture/items.ts',
        'src/lib/big-picture/on-screen-keyboard.ts',
        'src/lib/big-picture/big-picture-preferences.ts',
        'src/lib/big-picture/media-remote.ts',
        'src/lib/tier/tier-board.ts',
        'src/lib/tier/tier-editor-state.ts',
        'src/lib/tier/tier-candidates.ts',
        'src/lib/tier/tier-export-layout.ts',
        'src/lib/tier/tier-palette.ts',
        'src/lib/tier/tier-settings.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        statements: 80,
        branches: 70,
      },
    },
  },
});
