// Central registry of localStorage keys shared across settings, profile,
// media and AniList modules — keeps the string literal in one place so a
// typo can't silently create a second, disconnected copy of a preference.

export const STORAGE_KEYS = {
  customColor: 'metadea_custom_color',
  userBio: 'metadea_user_bio',
  ratingSystem: 'metadea_rating_system',
  activityBatchEpisodes: 'metadea_activity_batch_episodes',
  anilistToken: 'metadea_anilist_token',
  showAdultContent: 'metadea_show_adult_content',
  authToken: 'auth_token',
  authUsername: 'auth_username',
  appTheme: 'app_theme',
  userFavorite: 'user_favorite',
  localFolders: 'local_folders',
  envConfig: 'env_config',
  categoryRoutes: 'category_routes',
  monthlyHistory: 'monthly_history',
  userJourney: 'user_journey',
  profileAvatarCustom: 'profile_avatar_custom',
  profileBannerCustom: 'profile_banner_custom',
  shareAvatarCustom: 'share_avatar_custom',
  communityCatalogLastSync: 'community_catalog_last_sync',
  lastVisitedPath: 'metadea_last_visited_path',
  homeCalendarGeneralCache: 'metadea_home_calendar_general_cache',
  libraryGroupByBundle: 'metadea_library_group_by_bundle',
  searchState: 'metadea_search_state',
  updaterCheckedThisSession: 'metadea_updater_checked_this_session',
  locale: 'metadea_locale',
  profileSyncLastSync: 'metadea_profile_sync_last_sync',
  profileSyncLastAttempt: 'metadea_profile_sync_last_attempt',
  activityFeedLastFetch: 'metadea_activity_feed_last_fetch',
  activityFeedCache: 'metadea_activity_feed_cache',
  generalActivityFeedLastFetch: 'metadea_general_activity_feed_last_fetch',
  generalActivityFeedCache: 'metadea_general_activity_feed_cache',
  pendingLibraryType: 'metadea_pending_library_type',
  dualRatingEnabled: 'metadea_dual_rating_enabled',
  ratingName1: 'metadea_rating_name_1',
  ratingName2: 'metadea_rating_name_2',
  rating2System: 'metadea_rating_2_system',
  rating2Min: 'metadea_rating_2_min',
  rating2Max: 'metadea_rating_2_max',
  libraryActiveRatingSlot: 'metadea_library_active_rating_slot',
} as const;
