export const ALL_PLATFORMS = [
  "PC (Windows)",
  "Nintendo Switch",
  "Nintendo 3DS",
  "Nintendo DS",
  "Nintendo GameCube",
  "Nintendo 64",
  "Super Nintendo Entertainment System (SNES)",
  "Nintendo Entertainment System (NES)",
  "Wii",
  "Wii U",
  "Game Boy",
  "Game Boy Color",
  "Game Boy Advance",
  "PlayStation",
  "PlayStation 2",
  "PlayStation 3",
  "PlayStation 4",
  "PlayStation 5",
  "PlayStation Portable",
  "PlayStation Vita",
  "Xbox",
  "Xbox 360",
  "Xbox One",
  "Xbox Series X|S",
  "Sega Genesis",
  "Sega Saturn",
  "Sega Dreamcast",
  "Arcade",
  "Android",
  "iOS",
  "Mac",
  "Linux",
  "Oculus VR",
  "PlayStation VR",
  "Sega Game Gear",
  "N-Gage",
  "WonderSwan",
  "Neo Geo"
];

export const ALL_GENRES = [
  // IGDB Genres
  "Adventure",
  "Arcade",
  "Card & Board Game",
  "Fighting",
  "Hack and slash/Beat 'em up",
  "Indie",
  "MOBA",
  "Music",
  "Pinball",
  "Platform",
  "Point-and-click",
  "Puzzle",
  "Quiz/Trivia",
  "Racing",
  "Real-time strategy (RTS)",
  "Role-playing (RPG)",
  "Shooter",
  "Simulator",
  "Sport",
  "Sports",
  "Strategy",
  "Tactical",
  "Turn-based strategy (TBS)",
  "Visual Novel",
  
  // AniList Genres
  "Action",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Horror",
  "Mahou Shoujo",
  "Mecha",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Supernatural",
  "Thriller"
];
