// Central registry of localStorage keys shared across settings, profile,
// media and AniList modules — keeps the string literal in one place so a
// typo can't silently create a second, disconnected copy of a preference.

export const STORAGE_KEYS = {
  customColor: 'metadea_custom_color',
  userBio: 'metadea_user_bio',
  ratingSystem: 'metadea_rating_system',
  anilistToken: 'metadea_anilist_token',
  showAdultContent: 'metadea_show_adult_content',
  authToken: 'auth_token',
  authUsername: 'auth_username',
  appTheme: 'app_theme',
  userFavorite: 'user_favorite',
  localFolders: 'local_folders',
  envConfig: 'env_config',
  categoryRoutes: 'category_routes',
  monthlyHistory: 'monthly_history',
  userJourney: 'user_journey',
  profileAvatarCustom: 'profile_avatar_custom',
  profileBannerCustom: 'profile_banner_custom',
  shareAvatarCustom: 'share_avatar_custom',
  communityCatalogLastSync: 'community_catalog_last_sync',
  communityCatalogSyncedThisSession: 'metadea_community_catalog_synced_this_session',
  lastVisitedPath: 'metadea_last_visited_path',
  onboardingCompleted: 'metadea_onboarding_completed',
  onboardingStep: 'metadea_onboarding_step',
  homeCalendarGeneralCache: 'metadea_home_calendar_general_cache',
  libraryGroupByBundle: 'metadea_library_group_by_bundle',
  searchState: 'metadea_search_state',
  updaterCheckedThisSession: 'metadea_updater_checked_this_session',
  locale: 'metadea_locale',
  profileSyncLastSync: 'metadea_profile_sync_last_sync',
  profileSyncLastAttempt: 'metadea_profile_sync_last_attempt',
  activityFeedLastFetch: 'metadea_activity_feed_last_fetch',
  activityFeedCache: 'metadea_activity_feed_cache',
  generalActivityFeedLastFetch: 'metadea_general_activity_feed_last_fetch',
  generalActivityFeedCache: 'metadea_general_activity_feed_cache',
  pendingLibraryType: 'metadea_pending_library_type',
  dualRatingEnabled: 'metadea_dual_rating_enabled',
  ratingName1: 'metadea_rating_name_1',
  ratingName2: 'metadea_rating_name_2',
  rating2System: 'metadea_rating_2_system',
  rating2Min: 'metadea_rating_2_min',
  rating2Max: 'metadea_rating_2_max',
  libraryActiveRatingSlot: 'metadea_library_active_rating_slot',
  emulatorsConfig: 'emulators_config',
  romAutoRename: 'metadea_local_roms_auto_rename',
  unifySeasonsEnabled: 'metadea_unify_seasons_enabled',
  unifySeasonsHighestRatedCover: 'metadea_unify_seasons_highest_rated_cover',
  completedMangaIssueCover: 'metadea_completed_manga_issue_cover',
  mediaCoverPreferences: 'metadea_media_cover_preferences',
  libraryReleaseNotifications: 'metadea_library_release_notifications',
  jukeboxPreferences: 'metadea_jukebox_preferences',
  // "Watch for changes" dev toggle of the user UI themes (lib/ui-themes).
  uiThemeWatch: 'metadea_ui_theme_watch',
  // Local > Videojuegos: IGDB's launcher verdict per pending game, 7-day TTL
  // (lib/local/pending-launcher-memo.ts).
  pendingLauncherMemo: 'metadea_local_pending_launcher_memo',
  // Home's last rendered view-model, for an instant first paint
  // (lib/home/home-snapshot.ts), and the tiny layout hint derived from it
  // that home.astro's inline pre-paint script reads (it mirrors this
  // literal — see home-snapshot.test.ts).
  homeSnapshot: 'metadea_home_snapshot',
  homeLayoutHint: 'metadea_home_layout',
} as const;
